### The Machine Learning Process - 

data pre processing 

IMport the data, clean the data and split the data into training and test sets.


MOdelling
Build the model, train the model and make predictions.


Evaluation
Calculate performance metrics and make a verdict

###                                                    Data Preprocessing

In [12]:
#import the libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [28]:
# import the data, the endocing below as I encountered UnicodeDecodeError while trying to read a CSV file using pandas
df = pd.read_csv("Data.csv", encoding='ISO-8859-1')


In [29]:
df.head(5)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [31]:
#identiy the columns and rows. use iloc to take the indexes of the rows and the column
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [32]:
x = df.iloc[:, 1:-1].values # taking in all the values.take in all the columns excluding the last column in x
y = df.iloc[:, -1].values # take in the last column in y

In [42]:
missing_df = data.isna().sum()

print("Missing data per column:")
print(missing_df)


Missing data per column:
Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [33]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [34]:
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [35]:
#Sorting missing data

# Replace the missing value by the average of all the values. 
from sklearn.impute import SimpleImputer


In [36]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [37]:
# Select all numerical columns and exclude string values
imputer.fit(x[:, 1:3])

SimpleImputer()

In [39]:
# transform and enter the reolacement values

x[:, 1:3] = imputer.transform(x[:, 1:3])

In [40]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [46]:
# Encode categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [47]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')

In [48]:
x = np.array(ct.fit_transform(x))

In [49]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [50]:
# enconde the nos and yes into zeros and ones to convert the last dependable variable

from sklearn.preprocessing import LabelEncoder

In [51]:
le = LabelEncoder()

In [52]:
le.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [53]:
# splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split

In [54]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [55]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [56]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [57]:
print(y_train)

6     No
4    Yes
0     No
3     No
1    Yes
7    Yes
8     No
5    Yes
Name: Purchased, dtype: object


In [58]:
print(y_test)

2     No
9    Yes
Name: Purchased, dtype: object


In [59]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

In [60]:
sc = StandardScaler()# no arguments needed

In [61]:
x_train[:,3:] = sc.fit_transform(x_train[:,3:]) # applies the future scaling to x values

In [62]:
x_test[:,3:] = sc.fit_transform(x_test[:,3:])

In [63]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [64]:
print(x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
