In [8]:
w = list(range(19, 27))

In [9]:
w

[19, 20, 21, 22, 23, 24, 25, 26]

In [10]:
len(w)

8

In [11]:
type(w)

list

In [12]:
max(w)

26

In [13]:
min(w)

19

In [14]:
max(12, 345, 878, 456, -234)

878

        Packages
        Working with arrays. Arrays can only have one data types

In [19]:
import numpy as np

In [20]:
np.array(w)

array([19, 20, 21, 22, 23, 24, 25, 26])

In [21]:
a = np.array(w)

In [25]:
a.mean()

22.5

In [26]:
a.max()

26

In [27]:
a.mean()

22.5

In [28]:
z = np.array(list(range(20, 34)))

In [29]:
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [30]:
z[0:2]

array([20, 21])

In [31]:
z[1] = 34

In [32]:
z

array([20, 34, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [34]:
print((z[0] + z[2]))

42


In [35]:
z.sum()

384

In [36]:
np.sum(z)

384

In [37]:
c = z.copy()

In [38]:
c

array([20, 34, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [39]:
z

array([20, 34, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [40]:
c[0] = 34

In [41]:
c

array([34, 34, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [42]:
z

array([20, 34, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])