In [1]:
import numpy as np

In [2]:
x =np.arange(1,11)

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
x > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
x >= 6

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
bool_x = x > 5

In [12]:
bool_x

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [14]:
x[bool_x]

array([ 6,  7,  8,  9, 10])

In [13]:
x[x<5]

array([1, 2, 3, 4])

In [15]:
z = np.arange(50). reshape(5,10)

In [16]:
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
z [0][3]

3

In [19]:
x[1:3]

array([2, 3])

In [21]:
x =[1,2,3,4,5,6,7,7,7]

In [31]:
sum = [(49) / 34]
for sum in sum:
    print(sum)

1.4411764705882353


In [32]:
x = np.arange(0,11)

In [33]:
x + x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
x * x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [35]:
x / x

C:\Users\ojaga\AppData\Local\Temp\ipykernel_26220\1859513313.py:1: RuntimeWarning: invalid value encountered in divide
  x / x


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [36]:
x + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [37]:
x + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [43]:
x /x

1.0

In [44]:
z = np.arange(3*3)

In [45]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.sqrt(z)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [47]:
np.exp(z)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [48]:
np.tan(z)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146])

In [50]:
w = np.any(np.tan(z))

In [51]:
w

True

In [52]:
w = np.arange(0,0)

In [59]:
w = np.atleast_3d(3,4)

In [60]:
w

[array([[[3]]]), array([[[4]]])]

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [65]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [66]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [67]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.random.rand(1)

array([0.7506902])

In [71]:
np.random.randn(5)

array([0.73732267, 1.37071335, 0.12272519, 0.62059871, 0.45590872])

In [72]:
np.random.randint(5)

2

In [73]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [74]:
np.linspace(0.01, 1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [75]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [77]:
np.absolute(10)

10

In [80]:
np.sum(w)

7

In [85]:
w.sort()

In [86]:
w

[array([[[3]]]), array([[[4]]])]