In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [84]:
# import the dataset
df = pd.read_csv("Data.csv")

In [85]:
df.head(3)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56

In [86]:
x = df.iloc[:, :-1].values # taking in all the values.take in all the columns excluding the last column in x
y = df.iloc[:, -1].values # take in the last column in y

In [87]:
# Splitting the dataset into Training and Test set
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

Multiple Linear Regression

In [88]:
# train the dataset using multi Linear
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [89]:
# Predict the test result using Multi
y_pred = regressor.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [91]:
# Evaluate the model performance
# import the required libraries

from sklearn.metrics import r2_score

mlr = r2_score(y_test, y_pred)
mlr

0.9325315554761303

Polynomial Regression

In [92]:
# Training the Polynomial Regression model on the training set
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(x_train)
regressor = LinearRegression()
regressor.fit(x_poly, y_train)

LinearRegression()

In [93]:
# Predict the test result
y_pred = regressor.predict(poly_reg.transform(x_test))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.67 463.28]]


In [95]:
# Evaluate the model performance
# import the required libraries

from sklearn.metrics import r2_score

pr = r2_score(y_test, y_pred)
pr

0.9458193347147237

Support Vector Regression (SVR

In [96]:
# import the dataset
df = pd.read_csv("Data.csv")
x = df.iloc[:, :-1].values # taking in all the values.take in all the columns excluding the last column in x
y = df.iloc[:, -1].values # take in the last column in y

In [97]:
# reshape y for feature scaling
y = y.reshape(len(y), 1)

In [98]:
# Splitting the dataset
# Splitting the dataset into Training and Test set
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [99]:
# Feature Scaling - This is compulsory for SVR
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train)

In [100]:
# Training the SVR model on the Training set
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train, y_train)

C:\Users\ojaga\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [101]:
# Predict the test result
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [102]:
# Evaluate the model performance
# import the required libraries

from sklearn.metrics import r2_score

svr = r2_score(y_test, y_pred)
svr

0.948078404998626

Decision Tree Regression

In [103]:
# import the dataset
df = pd.read_csv("Data.csv")
x = df.iloc[:, :-1].values # taking in all the values.take in all the columns excluding the last column in x
y = df.iloc[:, -1].values # take in the last column in y

In [104]:
# Splitting the dataset into Training and Test set
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [105]:
# Training the decision tree on the whole dataset
from sklearn.tree import DecisionTreeRegressor

# create and instance / object
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [106]:
# Predict the test result 
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


In [108]:
# Evaluate the model performance
# import the required libraries

from sklearn.metrics import r2_score

dtr = r2_score(y_test, y_pred)
dtr

0.9615908334363876

In [112]:
print('multi Linear = ' , mlr)
print('Polynomial reg = ', pr)
print('Support Vector Regression = ', svr)
print(' Decision Tree Regression = ' , dtr)

multi Linear =  0.9325315554761303
Polynomial reg =  0.9458193347147237
Support Vector Regression =  0.948078404998626
 Decision Tree Regression =  0.9615908334363876
